### PR TITLE
Remove intrudr project page

### PR DESCRIPTION
**Pull request by byxor**
This post has remained empty for too long. I'm sure the other intrudr members won't mind.

### CODE REVIEW

**Comment by devoxel** [comment]
Just fill it in with details about how the project went :wink:

**Comment by byxor** [comment]
No.

**Comment by cliodhnaharrison** [comment]
Yeah I'm okay with this dying. Pretty sure Ciaran is too.

**Comment by iandioch** [comment]
Thanks xo

**Pull request merged**
